/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zsw_lesson_l32_Foo */

#ifndef _Included_com_zsw_lesson_l32_Foo
#define _Included_com_zsw_lesson_l32_Foo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zsw_lesson_l32_Foo
 * Method:    foo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zsw_lesson_l32_Foo_foo
  (JNIEnv *, jclass);

/*
 * Class:     com_zsw_lesson_l32_Foo
 * Method:    bar
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_zsw_lesson_l32_Foo_bar__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_zsw_lesson_l32_Foo
 * Method:    bar
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_zsw_lesson_l32_Foo_bar__Ljava_lang_String_2Ljava_lang_Object_2
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
