server:
  port: 18080

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: detect
  application:
    name: spring-boot-features
    admin:
      enabled: true
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    startup:
      enabled: true

config:
  name: ${spring.application.name}
  map:
    name: default

logging:
  config: classpath:logback-spring.xml

---
spring:
  config:
    activate:
      on-profile: dev
config:
  map:
    name: dev



---
spring:
  config:
    activate:
      on-profile: test
config:
  map:
    name: test