package com.zsw.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * @author ZhangShaowei
 */
@Data
@TableName("PRODUCT_INFO_INTERCITY")
public class ProductInfoIntercity implements Serializable {
    private static final long serialVersionUID = -3943468147263021666L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.ID
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.PRODUCT_TYPE_KEY
     */
    @TableField
    private String productTypeKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.PRODUCT_CODE
     */
    @TableField
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.NAME
     */
    @TableField
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.STATR_NAME
     */
    @TableField
    private String statrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.END_NAME
     */
    @TableField
    private String endName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.OUTBOUND_LINE
     */
    @TableField
    private Long outboundLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.INBOUND_LINE
     */
    @TableField
    private Long inboundLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.VEHICLE_SET
     */
    @TableField
    private String vehicleSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.VEHICLE_SET_STR
     */
    @TableField
    private String vehicleSetStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.PASSENGER_SET
     */
    @TableField
    private String passengerSet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.OPERATION_TIME_START
     */
    @TableField
    private String operationTimeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.OPERATION_TIME_END
     */
    @TableField
    private String operationTimeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.EFFECTIVE_DATE_START
     */
    @TableField
    private LocalDateTime effectiveDateStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.EFFECTIVE_DATE_END
     */
    @TableField
    private LocalDateTime effectiveDateEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.STATUS
     */
    @TableField
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.CREATOR
     */
    @TableField
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.CREATE_TIMESTAMP
     */
    @TableField
    private LocalDateTime createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.UPDATOR
     */
    @TableField
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.UPDATE_TIMESTAMP
     */
    @TableField
    private LocalDateTime updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.realNameTicketPurchase
     */
    @TableField
    private Integer realnameticketpurchase;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.realNameRide
     */
    @TableField
    private Integer realnameride;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_INFO_INTERCITY.DESCRIPTION
     */
    @TableField
    private String description;

}