server:
  port: 18083
  servlet:
    session:
      cookie:
        #         所有1/2级域名
        domain: bbxpc.com
#        name: JSESSION
spring:
  session:
    store-type: redis
    timeout: 24H
    redis:
      namespace: spring:session:bbxbackend
  redis:
    host: 106.15.43.157
    port: 26379
    password: Lanbbx24306
    database: 0
    lettuce:
      pool:
        max-active: 2
        max-idle: 1
logging:
  level:
    org.springframework.security: debug