server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.13:8848
        enabled: true
        register-enabled: true
        ephemeral: false

dubbo:
  provider:
    application:
      name: ${spring.application.name}
  protocols:
    dubbo:
      name: dubbo
      port: -1
#    rest:
#      name: rest
#      port: 9090
#      server: netty


