package com.zsw.quartz.persistence.mapper;

import com.zsw.quartz.persistence.entity.SystemJob;
import org.springframework.stereotype.Repository;

import java.util.HashMap;
import java.util.List;

@Repository
public interface SystemJobMapper {

    /**
     * 获取任务数量
     *
     * @param
     * @return
     */
    int getJobCount();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int insert(SystemJob record);

    /**
     * 查询定时任务列表
     *
     * @param map
     * @return
     */
    List<SystemJob> querySysJobList(HashMap<String, String> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int insertSelective(SystemJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    SystemJob selectByPrimaryKey(Integer id);

    /**
     * 根据bean查询定时任务详情
     *
     * @param
     * @return
     */
    SystemJob selectByBean(SystemJob bean);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_job
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemJob record);
}