server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 106.15.43.157:8848
        username: nacos
        password: nacos
        enabled: true
        register-enabled: true
        ephemeral: false

dubbo:
#  consumer:
#    check: false
  registry:
    address: nacos://192.168.1.13:8848
    register: true
  application:
    name: ${spring.application.name}
    id: ${spring.application.name}
    qos-enable: false
    qos-accept-foreign-ip: false
  protocol:
    id: dubbo
  protocols:
    dubbo:
      name: dubbo
      port: -1
#    rest:
#      name: rest
#      port: 9090
#      server: netty


