package com.zsw.persistence.mapper;

import com.zsw.persistence.entity.CountryLanguage;

public interface CountryLanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(CountryLanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    int insert(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    int insertSelective(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    CountryLanguage selectByPrimaryKey(CountryLanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CountryLanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CountryLanguage record);
}