package com.zsw.persistence.entity;

import lombok.Data;

@Data
public class Blob {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blob.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blob.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blob.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blob.comment
     *
     * @mbg.generated
     */
    private Comment comment;

}