package com.zsw.persistence.entity;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author ZhangShaowei
 */
@Data
public class Product implements Serializable {
    private static final long serialVersionUID = -4274211017134513436L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.id
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.name
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.number
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.status
     */
    private List<Integer> status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.createDate
     */
    private Date createDate;

}