package com.zsw.persistence.mapper;

import com.zsw.persistence.entity.Blob;

public interface BlobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blob
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blob
     *
     * @mbg.generated
     */
    int insert(Blob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blob
     *
     * @mbg.generated
     */
    int insertSelective(Blob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blob
     *
     * @mbg.generated
     */
    Blob selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blob
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Blob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_blob
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Blob record);
}