# redis 连接
spring:
  redis:
    host: 192.168.1.12
    port: 6379
    password: Anf34l_Fs
    database: 3
    lettuce:
      pool:
        max-active: 8
#        max-wait: -1
        max-idle: 8
#        min-idle: 0
#    timeout: 60

