server:
  port: 18081
  servlet:
    session:
      cookie:
        # 所有1/2级域名
        domain: example.com
        name: JSESSION
spring:
  session:
    store-type: redis
    redis:
      namespace: spring:session:bbxbackend
  redis:
    host: 192.168.1.12
    port: 6379
    password: Anf34l_Fs
    database: 15
    #    host: 106.15.43.157
    #    port: 26379
    #    password: Lanbbx24306
    #    database: 0
    lettuce:
      pool:
        max-active: 2
        max-idle: 1
