package com.zsw.quartz.persistence.entity;

public class SystemJob {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.job_name
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.job_group
     *
     * @mbg.generated
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.job_cron
     *
     * @mbg.generated
     */
    private String jobCron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.job_class_path
     *
     * @mbg.generated
     */
    private String jobClassPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.job_data_map
     *
     * @mbg.generated
     */
    private String jobDataMap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.job_status
     *
     * @mbg.generated
     */
    private Integer jobStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_job.job_describe
     *
     * @mbg.generated
     */
    private String jobDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.id
     *
     * @return the value of sys_job.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.id
     *
     * @param id the value for sys_job.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.job_name
     *
     * @return the value of sys_job.job_name
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.job_name
     *
     * @param jobName the value for sys_job.job_name
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.job_group
     *
     * @return the value of sys_job.job_group
     *
     * @mbg.generated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.job_group
     *
     * @param jobGroup the value for sys_job.job_group
     *
     * @mbg.generated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.job_cron
     *
     * @return the value of sys_job.job_cron
     *
     * @mbg.generated
     */
    public String getJobCron() {
        return jobCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.job_cron
     *
     * @param jobCron the value for sys_job.job_cron
     *
     * @mbg.generated
     */
    public void setJobCron(String jobCron) {
        this.jobCron = jobCron == null ? null : jobCron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.job_class_path
     *
     * @return the value of sys_job.job_class_path
     *
     * @mbg.generated
     */
    public String getJobClassPath() {
        return jobClassPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.job_class_path
     *
     * @param jobClassPath the value for sys_job.job_class_path
     *
     * @mbg.generated
     */
    public void setJobClassPath(String jobClassPath) {
        this.jobClassPath = jobClassPath == null ? null : jobClassPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.job_data_map
     *
     * @return the value of sys_job.job_data_map
     *
     * @mbg.generated
     */
    public String getJobDataMap() {
        return jobDataMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.job_data_map
     *
     * @param jobDataMap the value for sys_job.job_data_map
     *
     * @mbg.generated
     */
    public void setJobDataMap(String jobDataMap) {
        this.jobDataMap = jobDataMap == null ? null : jobDataMap.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.job_status
     *
     * @return the value of sys_job.job_status
     *
     * @mbg.generated
     */
    public Integer getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.job_status
     *
     * @param jobStatus the value for sys_job.job_status
     *
     * @mbg.generated
     */
    public void setJobStatus(Integer jobStatus) {
        this.jobStatus = jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_job.job_describe
     *
     * @return the value of sys_job.job_describe
     *
     * @mbg.generated
     */
    public String getJobDescribe() {
        return jobDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_job.job_describe
     *
     * @param jobDescribe the value for sys_job.job_describe
     *
     * @mbg.generated
     */
    public void setJobDescribe(String jobDescribe) {
        this.jobDescribe = jobDescribe == null ? null : jobDescribe.trim();
    }
}